# Nombre con que se registra la aplicación
spring.application.name=eureka

# Puerto estándar para Eureka Server y escuchar peticiones HTTP
server.port=8761

# Evita que Eureka Server se registre a sí mismo en el servidor Eureka.
eureka.client.register-with-eureka=false

# Evita que Eureka Server obtenga el registro de otros servidores Eureka.
eureka.client.fetch-registry=false

# Prefiere la dirección IP en lugar del hostname para identificar la instancia.
eureka.instance.prefer-ip-address=true
